### ISSUE TITLE
Repostitory structure for main is not compliant

### ISSUE THREAD

**Issue by tobiaskuntzsch** [markussiebert/homeassistant-addon#1]
Then i try to add the custom HACs repository i get the error message:

`Repostitory structure for main is not compliant`

Repository:
https://github.com/markussiebert/home-assistant-addons

Category:
Integration

HACs:
Integrations Version: | 1.17.2
Frontend Version: | 20211114224857

Home Assistant 2021.11.5

**Comment by markussiebert** [comment]
Oh, it's not a HACS Repository, it's a supervisor repository 

![image](https://user-images.githubusercontent.com/16692560/142914290-47530098-5c51-4a7f-a123-582f4cb5e60d.png)

**Comment by markussiebert** [comment]
messed I something up in the docs?

**Comment by tobiaskuntzsch** [comment]
-
